#!bin/bash                                                                                                                            
input="utils.txt"
while IFS= read -r line
do
    
    find ./$line -type f -name "*.config" -exec sed -i '/\<close_stream\>/{d}' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<i_ring_push\>/{d}' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<ind\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<copy_internal\>/{d}' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<expr\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<human_readable\>/{d}' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<adjust_value\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<keycmp\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<do_stat\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<isdst_differ\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<iwrite\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<memcmp2\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<print_numbers\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<xstrtold\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<elide_tail_bytes_pipe\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<parse_datetime\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<parse_datetime2\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<argmatch_valid\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<re_search_internal\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<update_cur_sift_state\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<sift_states_backward\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<sub_epsilon_src_nodes\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<re_acquire_state_context\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<is_basic\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<version_etc\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<version_etc_va\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<re_acquire_state\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<re_string_reconstruct\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<build_trtable\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<build_wcs_upper_buffer\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<register_state\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<build_charclass_op\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<rpl_fts_read\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<fts_build\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<rpl_fts_open\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<enter_dir\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<argmatch\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<check_arrival\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<check_dst_limits\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<transit_state_bkref\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<add_exclude\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<rpl_regcomp\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<load_buffer\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<mem_cd_iconv\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<read_file_system_list\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<mktime_z\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<revert_tz\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<set_tz\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<strintcmp\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<mbsstr_trimmed_wordbounded\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<md5_buffer\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<mbsstr_trimmed_wordbounded\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<isaac_refill\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<strnumcmp\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<mergefps\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<isaac_refill\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<strnumcmp\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<mmalloca\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<factor_using_pollard_rho2\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<gcd2_odd\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<sequential_sort\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<prep_non_filename_text\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<print_long_values\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<abformat_init\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<group_number\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<gobble_file\>/d' {} +
    find ./$line -type f -name "*.config" -exec sed -i '/\<print_long_format\>/d' {} +


    echo "done"
    
done < "$input"
